### ISSUE TITLE
convert to python readable file format

### ISSUE THREAD

**Issue by StephanieMoe** [BrillouinMicroscopy/BrillouinEvaluation#19]
Dear Raimund,
could you please adds something like

save(’results.mat’,’results' ‚-v7.3‘)

damit ich das ausgewertete Brillouinmap file als h5 file in Python öffnen kann? 

Danke! VG Stephanie

**Comment by raimund-schluessler** [comment]
Yes, we can add this. In the meantime you can just load the file with Matlab and save it yourself with the correct parameters.
