### ISSUE TITLE
Implement exporting Brillouin data maps to HDF5

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/BrillouinEvaluation#26]
For loading the Brillouin data into the masking software, we need to export the data to a HDF5 file. The file should include:

- a dataset for each channel, e.g. Brillouin shift, Brillouin peak intensity, time, etc.
- the scale in x- and y-direction respectively

@paulmueller Do you prefer a certain structure for the storage, e.g. a group for each channel or just multiple datasets at the root level?

Also @StephanieMoe for reference.

**Comment by raimund-schluessler** [comment]
Related to #19.

**Comment by paulmueller** [comment]
I would prefer a flat file structure (multiple datasets at the root level). Also, I think it should be sufficient for now to only store the averaged data of the peaks (as we discussed today). Everything else would only be confusing to the average user.
